//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/GameScene/Player/InputSystem.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputSystem: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputSystem"",
    ""maps"": [
        {
            ""name"": ""PlayerInput"",
            ""id"": ""cbf2d1a7-b95b-4801-ba10-2b6e8933bf44"",
            ""actions"": [
                {
                    ""name"": ""Moving"",
                    ""type"": ""PassThrough"",
                    ""id"": ""13045fd1-69c6-48f4-a941-6830b0dc22ca"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""852e3f31-c5a4-40bf-a62b-bfedad0cbe2d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""638dfdeb-d75c-42c0-a539-a8b6e9d65480"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleInventory"",
                    ""type"": ""Button"",
                    ""id"": ""0a1f512c-414d-47f3-a6ad-3ad0f65efb25"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectHandSlot_1"",
                    ""type"": ""Button"",
                    ""id"": ""045fe4ba-8365-421e-955c-917f37a88c82"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectHandSlot_2"",
                    ""type"": ""Button"",
                    ""id"": ""5a6ac063-caaa-4396-832b-c10009e81859"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectHandSlot_3"",
                    ""type"": ""Button"",
                    ""id"": ""7df84a26-0ed3-465c-8a9b-584ae2138652"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectHandSlot_4"",
                    ""type"": ""Button"",
                    ""id"": ""ca2d60d2-8c16-48a8-a24a-386a303f323f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem"",
                    ""type"": ""Button"",
                    ""id"": ""22e86dfe-6064-463f-b1ad-69f6566e8ead"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""1f726b9a-d34a-4b97-95de-b8f410030b41"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f5db5497-e1e9-4821-ac21-2a68461b6b94"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bd295341-344a-4891-b7b4-0dbc82cdd3f5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""14fe599f-6eb8-4863-81e1-f468ecc70090"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c1c16feb-032c-4efd-b06a-dca75f6575f3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""adf36507-132b-4b8f-9ed4-43e7d53fe7bc"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af5793d0-df39-4bc9-99c6-772e141d4ecc"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""504d7c6a-352c-4697-813e-be887856a85a"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63e8cfe3-99a1-4719-a789-b5f5ea52ddf8"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectHandSlot_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""890f8aed-599b-43de-b79d-cac2f4611f0b"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectHandSlot_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""126e60d0-0342-4a23-80c2-8a6b23689896"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectHandSlot_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91b6792a-b8f5-4505-811e-289cce3edf54"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectHandSlot_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b6e8edd-e6e3-4dbe-83db-6c2a8fb92be3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerInput
        m_PlayerInput = asset.FindActionMap("PlayerInput", throwIfNotFound: true);
        m_PlayerInput_Moving = m_PlayerInput.FindAction("Moving", throwIfNotFound: true);
        m_PlayerInput_MousePosition = m_PlayerInput.FindAction("MousePosition", throwIfNotFound: true);
        m_PlayerInput_Run = m_PlayerInput.FindAction("Run", throwIfNotFound: true);
        m_PlayerInput_ToggleInventory = m_PlayerInput.FindAction("ToggleInventory", throwIfNotFound: true);
        m_PlayerInput_SelectHandSlot_1 = m_PlayerInput.FindAction("SelectHandSlot_1", throwIfNotFound: true);
        m_PlayerInput_SelectHandSlot_2 = m_PlayerInput.FindAction("SelectHandSlot_2", throwIfNotFound: true);
        m_PlayerInput_SelectHandSlot_3 = m_PlayerInput.FindAction("SelectHandSlot_3", throwIfNotFound: true);
        m_PlayerInput_SelectHandSlot_4 = m_PlayerInput.FindAction("SelectHandSlot_4", throwIfNotFound: true);
        m_PlayerInput_UseItem = m_PlayerInput.FindAction("UseItem", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInput
    private readonly InputActionMap m_PlayerInput;
    private List<IPlayerInputActions> m_PlayerInputActionsCallbackInterfaces = new List<IPlayerInputActions>();
    private readonly InputAction m_PlayerInput_Moving;
    private readonly InputAction m_PlayerInput_MousePosition;
    private readonly InputAction m_PlayerInput_Run;
    private readonly InputAction m_PlayerInput_ToggleInventory;
    private readonly InputAction m_PlayerInput_SelectHandSlot_1;
    private readonly InputAction m_PlayerInput_SelectHandSlot_2;
    private readonly InputAction m_PlayerInput_SelectHandSlot_3;
    private readonly InputAction m_PlayerInput_SelectHandSlot_4;
    private readonly InputAction m_PlayerInput_UseItem;
    public struct PlayerInputActions
    {
        private @InputSystem m_Wrapper;
        public PlayerInputActions(@InputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @Moving => m_Wrapper.m_PlayerInput_Moving;
        public InputAction @MousePosition => m_Wrapper.m_PlayerInput_MousePosition;
        public InputAction @Run => m_Wrapper.m_PlayerInput_Run;
        public InputAction @ToggleInventory => m_Wrapper.m_PlayerInput_ToggleInventory;
        public InputAction @SelectHandSlot_1 => m_Wrapper.m_PlayerInput_SelectHandSlot_1;
        public InputAction @SelectHandSlot_2 => m_Wrapper.m_PlayerInput_SelectHandSlot_2;
        public InputAction @SelectHandSlot_3 => m_Wrapper.m_PlayerInput_SelectHandSlot_3;
        public InputAction @SelectHandSlot_4 => m_Wrapper.m_PlayerInput_SelectHandSlot_4;
        public InputAction @UseItem => m_Wrapper.m_PlayerInput_UseItem;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerInputActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Add(instance);
            @Moving.started += instance.OnMoving;
            @Moving.performed += instance.OnMoving;
            @Moving.canceled += instance.OnMoving;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @ToggleInventory.started += instance.OnToggleInventory;
            @ToggleInventory.performed += instance.OnToggleInventory;
            @ToggleInventory.canceled += instance.OnToggleInventory;
            @SelectHandSlot_1.started += instance.OnSelectHandSlot_1;
            @SelectHandSlot_1.performed += instance.OnSelectHandSlot_1;
            @SelectHandSlot_1.canceled += instance.OnSelectHandSlot_1;
            @SelectHandSlot_2.started += instance.OnSelectHandSlot_2;
            @SelectHandSlot_2.performed += instance.OnSelectHandSlot_2;
            @SelectHandSlot_2.canceled += instance.OnSelectHandSlot_2;
            @SelectHandSlot_3.started += instance.OnSelectHandSlot_3;
            @SelectHandSlot_3.performed += instance.OnSelectHandSlot_3;
            @SelectHandSlot_3.canceled += instance.OnSelectHandSlot_3;
            @SelectHandSlot_4.started += instance.OnSelectHandSlot_4;
            @SelectHandSlot_4.performed += instance.OnSelectHandSlot_4;
            @SelectHandSlot_4.canceled += instance.OnSelectHandSlot_4;
            @UseItem.started += instance.OnUseItem;
            @UseItem.performed += instance.OnUseItem;
            @UseItem.canceled += instance.OnUseItem;
        }

        private void UnregisterCallbacks(IPlayerInputActions instance)
        {
            @Moving.started -= instance.OnMoving;
            @Moving.performed -= instance.OnMoving;
            @Moving.canceled -= instance.OnMoving;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @ToggleInventory.started -= instance.OnToggleInventory;
            @ToggleInventory.performed -= instance.OnToggleInventory;
            @ToggleInventory.canceled -= instance.OnToggleInventory;
            @SelectHandSlot_1.started -= instance.OnSelectHandSlot_1;
            @SelectHandSlot_1.performed -= instance.OnSelectHandSlot_1;
            @SelectHandSlot_1.canceled -= instance.OnSelectHandSlot_1;
            @SelectHandSlot_2.started -= instance.OnSelectHandSlot_2;
            @SelectHandSlot_2.performed -= instance.OnSelectHandSlot_2;
            @SelectHandSlot_2.canceled -= instance.OnSelectHandSlot_2;
            @SelectHandSlot_3.started -= instance.OnSelectHandSlot_3;
            @SelectHandSlot_3.performed -= instance.OnSelectHandSlot_3;
            @SelectHandSlot_3.canceled -= instance.OnSelectHandSlot_3;
            @SelectHandSlot_4.started -= instance.OnSelectHandSlot_4;
            @SelectHandSlot_4.performed -= instance.OnSelectHandSlot_4;
            @SelectHandSlot_4.canceled -= instance.OnSelectHandSlot_4;
            @UseItem.started -= instance.OnUseItem;
            @UseItem.performed -= instance.OnUseItem;
            @UseItem.canceled -= instance.OnUseItem;
        }

        public void RemoveCallbacks(IPlayerInputActions instance)
        {
            if (m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerInputActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerInputActions @PlayerInput => new PlayerInputActions(this);
    public interface IPlayerInputActions
    {
        void OnMoving(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnToggleInventory(InputAction.CallbackContext context);
        void OnSelectHandSlot_1(InputAction.CallbackContext context);
        void OnSelectHandSlot_2(InputAction.CallbackContext context);
        void OnSelectHandSlot_3(InputAction.CallbackContext context);
        void OnSelectHandSlot_4(InputAction.CallbackContext context);
        void OnUseItem(InputAction.CallbackContext context);
    }
}
